### ISSUE TITLE
提议在腾讯会议分享ppt

### ISSUE THREAD

**Issue by zhuocai** [saturn-lab/STIS-2020S#32]
如果不麻烦的话，在腾讯会议上也放ppt，需要演示其他内容的时候再随时切换桌面。因为电脑上看ppt看的稍微舒服一点。

如果太麻烦就不必了

**Comment by ritou11** [comment]
@zhenchen3419 还请陈老师反馈意见

**Comment by zhenchen3419** [comment]
Good Idea！没问题的。
